apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:ULf0yxEptRzPV1THTIXsgriiTNpKg7Lm12D/xSthX9/7KFXokiNKThmEGXnaaJ7jc8uaEQYuPbkzX1W+FpYv,iv:NYdiWOmrNK1O5LyFNBsgSvV+MMMNZGSjm9ah+0tNZe8=,tag:ZYKv3aWHbnx7uQ53JOgqyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ntv069qzs5hc4wgk8nyutkhhrnmv9hvgx4q6henctqse5kcz29qqje6ysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb21CWlppRnBXeVI5MUJq
            OGkyc0tBdGZmbEJEc2Z4SDJEU3grQ00rdHdzCnpqOE9CZ0pSMG8vbncyekVtU1M4
            K0tHMUJyTkhPd0FPc2JOQmtVWnY5dlUKLS0tIFhQWWJWaDNxTWhyN3NPTy9GcmVu
            MUMxQnBJdVE2UTNDMTlaTHJ6cFRzdlkK87FwruJo/Oe714IWK+YVzzyw5r6XlxpM
            C0PRZcLpmF5lQAxj7SEopo1iqqikB09bUgpViI0dqLTnaVkQmCN2AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T23:16:30Z"
    mac: ENC[AES256_GCM,data:l/EXRAC62Q8vEnTEldOjeIMoKiONyVLKP13eLuiS/LtqbgPeVQb7H/P+LwCJt+UpQ2EIQSVACH/bS6RuyfvLGocUg73jT8x6ctIRS3Qa0oVk097e19Nkf9imeITmOA3YL//C94BoLXWJyRuM4nlXT9qBFDxYxd1xjlWfQnuRAgM=,iv:fM16Jsc1Aol6zy4v7M9wADsAbmoeTixznwn8hpozJXw=,tag:UxVdn0QiDFPMwtx7XGIEyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
