apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:w1aQIQC7nFaGFDs1QCrZ5pkX0TikxmVfQ8gjdCWu6U9Yj0ayjoCUARSyTCLQXYypOe22o2URckleCTYUfuuF,iv:A+5/wNQp53FEGtiwNt/T2l3FMvOmu/B3lLYj6H/6kh0=,tag:UTgPRu00XGkKhPYHdK5UOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ntv069qzs5hc4wgk8nyutkhhrnmv9hvgx4q6henctqse5kcz29qqje6ysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSlhQRm9VRTJrOU1QK0N2
            K1JwMUNCVEVaMGtkTEVVMi9ndnNnU0dMYWhRCnBwd3owMXFoRHpSVC9Yb3RaMStk
            Vzl5VVh1a0txWnYwS1MyZ21KRTkwclUKLS0tIDJxamlNVXlzeWRyRWd4YzcxVDJs
            S25md1N1cm9zUHF6Q1dkNDNVdkpVYnMKhxv3oG/BNhEOslcbcOiM/F4XdhjFZ2kb
            otTkN99ltK5GYv+jagQHiiLbI4cF+NgbRxtlnKZv3TVr8q6Om7CfMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T23:52:30Z"
    mac: ENC[AES256_GCM,data:knsUGxwOoRXkANrLGSXVt65cgaUgmlq4BdERBdP24cpWeOx49fppY4/WpqOMx0i+iZS2wzyvV4vQtDGEQMXsxZV5GgeSxf3I/GjoujZdATxz+gB0mr1bv9Vl/8PH7c9bHk4ZuwhmRMcNw1lKDYpYPqyeBmJcPnv70E+ExtByuVY=,iv:MUh8MD2mlBw19XCIFsnRAQ+7qv47ZJeMUaleebIpP88=,tag:ERYytpGjZ876tpa75Zirow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
