---
- name: Create infrastructure with Terraform
  hosts: localhost
  become: true
  roles:
    - role: diodonfrost.terraform
  vars_files:
    - "vars/ansible_vault.yaml"
  vars:
    terraform_dir: ../terraform

  tasks:
    - name: Terraform
      ansible.builtin.debug:
        msg: Terraform is installed

- name: Create infrastructure with Terraform
  hosts: localhost
  roles:
    - role: diodonfrost.terraform
  vars_files:
    - "vars/ansible_vault.yaml"
  vars:
    terraform_dir: ../terraform
  tasks:
    - name: Create instances with Terraform
      community.general.terraform:
        project_path: "{{ terraform_dir }}"
        state: present
        complex_vars: true
        force_init: true
        variables:
          provider_vsphere_host: "{{ vcenter_host }}"
          provider_vsphere_user: "{{ vcenter_user }}"
          provider_vsphere_password: "{{ vcenter_password }}"
          cluster_nodes: "{{ cluster }}"
      register: output
