apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:MKQbMt8e3QQP3JeNWS+PNShuv7/X2n3+8WiHqjoveU5HLM3fYudbeQ==,iv:E//I7V6ue38+HkHexapJah+d0x0jVJcL84V6UwSnJkA=,tag:yr9L/mXXZbxWPtmlkadjMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ntv069qzs5hc4wgk8nyutkhhrnmv9hvgx4q6henctqse5kcz29qqje6ysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb1d1R2VVZWRUbExHTHQx
            YllDN2lSS0VkSnMzbHRIb3NyVGpacXRwV0hVCmFkclZmcW9ad3QrNHZQMUZnd1RT
            MTF6QlMwU0Zpc3NkaytENFRXYnZTamcKLS0tIDB0TFc2OElGK2NBaTAxSlZITi9j
            R1Q0K1VKeURlbmg2bFY3b0t4b1JEem8KEyp6RcrT+6N+Lh2UmhYTr7q9Kxog6Ugg
            qoeIzRYR9GVY0cBLfci9XHV+KczW4YftstOq2WXhZ9BEPk3uArl8pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-05T23:52:30Z"
    mac: ENC[AES256_GCM,data:q2WGhoPz4iajICEc+yUUUAptEqrelkt4Yg6UYibH0qsKHKKKawZYeLbf0A7uu3HTwBjNT0Fgmq1OrgvIj+SHoFfX2WB/imCogKjz9R0dOlL8VtdUJVdI4voOKL/sF03tgY+fn08uVCCwrggbs/5/5Rx+kuEripdEs8zPwhB+mh4=,iv:s3Qoo3c2kZGMwepDfbRWeKcEI4dmQyJg2yLuKofBJd0=,tag:CpjzXOk6L623uxBqUx6Hog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
