apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:0zLlrsUal3/Ih9UZ68IdXwH2htS0bVKpH/5UdMm1juA=,iv:wcRSCY6/oX2CRcetpHnx66APTsIvzhLp/Di4Ddcvt2c=,tag:DKNmDNouWEBVpkvJ1uRjqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ntv069qzs5hc4wgk8nyutkhhrnmv9hvgx4q6henctqse5kcz29qqje6ysa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbWRiVS9zQzdTSFkzUGF2
            d3V1KzBXQ2JHMDlzcERRMTNvNGFBZDBHdVM4CmpSc3VLSSs5NmhrY0lvdVVGNWMz
            MFZwVVZqSnI0WTEyUkVDLzBvWTlIK1EKLS0tIENidERiT0NkV21nYlZtbC9IOHZI
            TzhnYzhaQ0NzcmFKbWlCZ0NKZUpqUDgKu+gLYpUNzc8RJYcjknWTfz1a2CIUlvyg
            YVxyznJ02Uwi7bqBecdHWFNvzbS0nalZn2M6pBNHkyqrPLEmQ4G8bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-06T00:08:05Z"
    mac: ENC[AES256_GCM,data:9FJ4Tp2QdtOkJW1qIkuTPzF2QVXV5QPZZmZxgfGXX7TERbuDeIldDVFV8cZcWjdS8ssRfqHiwDSY10UaEJKtE6ws/Hexk1ijrma6LoTq/6H4kmZP2YvnZ1CiS8ghYz3pnNojBKFkW1XWN5Nxq3F0BpUngOAk8C4odm+A99KU8O4=,iv:olE4FB17mYDbI5dk7gWQJu2tSzF0ACeWZkoH5XxyHfM=,tag:3YaSjsFMHjilrYYcV6CDnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
